image:
  repository: testlsclusterregistry.azurecr.io/microservices/hello
  tag: v2
  pullPolicy: Always

imagePullSecrets:
  - name: acr-authn

serviceAccount:
  create: true
  name: "lssvcaccount"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

tolerations: []

nodeSelector: {}

affinity: {}
